load subtopics_discriminant.mat

dist_threshold = 5.2;
x_yes = x_train(x_train(:,end) < dist_threshold, 1:end-1);
x_no  = x_train(x_train(:,end) >= dist_threshold, 1:end-1);
[total_yes, ~] = size(x_yes);
[total_no, ~]  = size(x_no);

[~, subtopic_indices] = sort(abs(subtopics_discriminant), 'descend');
n_subtopics = 20;
top_subtopics = subtopic_indices(1:n_subtopics);
subtopic_labels = { ...
  'db', ...
  'lb', ...
  'cinnabon', ...
  'happen', ...
  'mani', ...
  'gee', ...
  'garrett', ...
  'dennoch', ...
  'charlott', ...
  'uk', ...
  'lo', ...
  'greas', ...
  'stripper', ...
  'peut', ...
  'luckili', ...
  'etait', ...
  'thin', ...
  'lindsay', ...
  'cabeza', ...
  'cheski' ...
};

filter_labels = [1 2 3 4 6 7 12 13 15 17];
n_subtopics = length(filter_labels);
top_subtopics = top_subtopics(filter_labels);
subtopic_labels = subtopic_labels(filter_labels);

figure(4);
subplot(2,2,2);
bar(1:n_subtopics, total_yes*3*diag(mu_x_yes_subtopics(top_subtopics)), 'stacked');
axis([0 11 0 2500]);
title('Mean subtopics, within 5.2mi of college');
xlabel('Subtopics');
ylabel('Number of occurrences');

subplot(2,2,4);
bar(1:n_subtopics, total_no*3*diag(mu_x_no_subtopics(top_subtopics)), 'stacked');
axis([0 11 0 2500]);
title('Mean subtopics, outside 5.2mi of college');
xlabel('Subtopics');
ylabel('Number of occurrences');

subplot(2,2,[1 3]);
bar(1:n_subtopics, diag(-subtopics_discriminant(top_subtopics)), 'stacked');
axis([0 11 -0.35 0.35]);
title('Discriminant subtopics');
xlabel('Subtopics');
ylabel('Subtopic discriminant');
legend(subtopic_labels{:}, 'Location', 'southoutside');
